import itertools
counter=itertools.count(start=5,step=3)
print(counter)
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
counter=itertools.count(start=5,step=-3)
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
